version: "3.8"
services:

  db_main:
    container_name: cryptobot_db_main
    image: postgres:12
    environment:
      POSTGRES_DB: cryptobot
      POSTGRES_USER: cryptobot
      POSTGRES_PASSWORD: cryptobot
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cryptobot"]
      interval: 5s
      timeout: 2s
      retries: 10

  db_test:
    container_name: cryptobot_db_test
    image: postgres:12
    environment:
      POSTGRES_DB: cryptobot_test
      POSTGRES_USER: cryptobot_test
      POSTGRES_PASSWORD: cryptobot_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cryptobot_test"]
      interval: 5s
      timeout: 2s
      retries: 10
